nfts = [{'Collection': 'goblintown.wtf',
  '24 hs %': 56.77,
  '7 d %': 562.01,
  'Owners': 4500,
  'Items': 10000,
  'Category': 'New',
  'Chain': 'Ethereum',
  'Twitter followers': 39500,
  'Ownership %': 45.0,
  'Volume (USD) in M': 23.21621268,
  'Floor (USD)': 5318.136,
  'Gas Volume (USD) in M': 0.225,
  'Market Share %': 63.14,
  'Growth': 'Hot - buy now',
  'Ownership Status': 'Low OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Chimpers',
  '24 hs %': -35.62,
  '7 d %': -73.58,
  'Owners': 2800,
  'Items': 5600,
  'Category': 'New',
  'Chain': 'Ethereum',
  'Twitter followers': 106700,
  'Ownership %': 50.0,
  'Volume (USD) in M': 15.16028193,
  'Floor (USD)': 3631.0032,
  'Gas Volume (USD) in M': 0.14,
  'Market Share %': 41.23,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'GENE_SIS: The Girls of Armament',
  '24 hs %': -42.52,
  '7 d %': -29.29,
  'Owners': 4500,
  'Items': 10000,
  'Category': 'New',
  'Chain': 'Ethereum',
  'Twitter followers': 236800,
  'Ownership %': 45.0,
  'Volume (USD) in M': 10.19737907,
  'Floor (USD)': 385.1064,
  'Gas Volume (USD) in M': 0.225,
  'Market Share %': 27.73,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'AINightbirds',
  '24 hs %': -53.6,
  '7 d %': 0.0,
  'Owners': 4700,
  'Items': 10000,
  'Category': 'New',
  'Chain': 'Ethereum',
  'Twitter followers': 11200,
  'Ownership %': 47.0,
  'Volume (USD) in M': 9.186401419,
  'Floor (USD)': 421.7832,
  'Gas Volume (USD) in M': 0.235,
  'Market Share %': 24.98,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Moonbirds Oddities',
  '24 hs %': -18.56,
  '7 d %': 0.0,
  'Owners': 6200,
  'Items': 10000,
  'Category': 'New',
  'Chain': 'Ethereum',
  'Twitter followers': 201900,
  'Ownership %': 62.0,
  'Volume (USD) in M': 6.842698884,
  'Floor (USD)': 5024.7216,
  'Gas Volume (USD) in M': 0.31,
  'Market Share %': 18.61,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Rarible',
  '24 hs %': -1.81,
  '7 d %': -45.79,
  'Owners': 214100,
  'Items': 315700,
  'Category': 'Art',
  'Chain': 'Ethereum',
  'Twitter followers': 477100,
  'Ownership %': 67.81754831,
  'Volume (USD) in M': 185.5226059,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 10.705,
  'Market Share %': 504.56,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Community',
  'Accesibility': 'Not interesting',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'SuperRare',
  '24 hs %': -94.3,
  '7 d %': -42.0,
  'Owners': 6800,
  'Items': 31700,
  'Category': 'Art',
  'Chain': 'Ethereum',
  'Twitter followers': 314200,
  'Ownership %': 21.4511041,
  'Volume (USD) in M': 123.0906417,
  'Floor (USD)': 275.076,
  'Gas Volume (USD) in M': 0.34,
  'Market Share %': 334.76,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Karafuru',
  '24 hs %': -80.87,
  '7 d %': -58.61,
  'Owners': 3700,
  'Items': 5600,
  'Category': 'Art',
  'Chain': 'Ethereum',
  'Twitter followers': 419700,
  'Ownership %': 66.07142857,
  'Volume (USD) in M': 79.86494233,
  'Floor (USD)': 1925.532,
  'Gas Volume (USD) in M': 0.185,
  'Market Share %': 217.2,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Mutant Ape Tatch Club',
  '24 hs %': -42.63,
  '7 d %': -8.89,
  'Owners': 12600,
  'Items': 19400,
  'Category': 'Collectibles',
  'Chain': 'Ethereum',
  'Twitter followers': 1900,
  'Ownership %': 64.94845361,
  'Volume (USD) in M': 743.5259718,
  'Floor (USD)': 29873.2536,
  'Gas Volume (USD) in M': 0.63,
  'Market Share %': 2022.13,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Emerging',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Azuki',
  '24 hs %': -31.67,
  '7 d %': -0.48,
  'Owners': 5100,
  'Items': 10000,
  'Category': 'Collectibles',
  'Chain': 'Ethereum',
  'Twitter followers': 311600,
  'Ownership %': 51.0,
  'Volume (USD) in M': 447.8615968,
  'Floor (USD)': 18044.9856,
  'Gas Volume (USD) in M': 0.255,
  'Market Share %': 1218.02,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Clone X  X TAKASHI MURAKAMI',
  '24 hs %': -31.24,
  '7 d %': -39.13,
  'Owners': 9300,
  'Items': 19300,
  'Category': 'Collectibles',
  'Chain': 'Ethereum',
  'Twitter followers': 26,
  'Ownership %': 48.1865285,
  'Volume (USD) in M': 375.0538759,
  'Floor (USD)': 22372.848,
  'Gas Volume (USD) in M': 0.465,
  'Market Share %': 1020.01,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Emerging',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'ENS: Ethereum Name Service',
  '24 hs %': -1.741,
  '7 d %': -26.23,
  'Owners': 400500,
  'Items': 1200000,
  'Category': 'Domain Names',
  'Chain': 'Ethereum',
  'Twitter followers': 312,
  'Ownership %': 33.375,
  'Volume (USD) in M': 56.27765213,
  'Floor (USD)': 18.3384,
  'Gas Volume (USD) in M': 20.025,
  'Market Share %': 153.06,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Emerging',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Unstoppable Domains',
  '24 hs %': 2750.0,
  '7 d %': -53.25,
  'Owners': 64600,
  'Items': 319000,
  'Category': 'Domain Names',
  'Chain': 'Ethereum',
  'Twitter followers': 254900,
  'Ownership %': 20.2507837,
  'Volume (USD) in M': 2.217479328,
  'Floor (USD)': 18.3384,
  'Gas Volume (USD) in M': 3.23,
  'Market Share %': 6.03,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Community',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Decentraland Names',
  '24 hs %': -100.0,
  '7 d %': 104.93,
  'Owners': 13300,
  'Items': 34000,
  'Category': 'Domain Names',
  'Chain': 'Ethereum',
  'Twitter followers': 2235,
  'Ownership %': 39.11764706,
  'Volume (USD) in M': 1.601327426,
  'Floor (USD)': 55.0152,
  'Gas Volume (USD) in M': 0.665,
  'Market Share %': 4.36,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Emerging',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Shark',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Cryptovoxels Nammes',
  '24 hs %': 0.0,
  '7 d %': -100.0,
  'Owners': 2600,
  'Items': 9500,
  'Category': 'Domain Names',
  'Chain': 'Ethereum',
  'Twitter followers': 81800,
  'Ownership %': 27.36842105,
  'Volume (USD) in M': 0.029433132,
  'Floor (USD)': 55.0152,
  'Gas Volume (USD) in M': 0.13,
  'Market Share %': 0.08,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Fish',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Domains.Kred',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 17,
  'Items': 24,
  'Category': 'Domain Names',
  'Chain': 'Ethereum',
  'Twitter followers': 56500,
  'Ownership %': 70.83333333,
  'Volume (USD) in M': 0.0108379944,
  'Floor (USD)': 7151.976,
  'Gas Volume (USD) in M': 0.00085,
  'Market Share %': 0.03,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Fish',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'WVRPS by WarpSound (Official)',
  '24 hs %': 132.5,
  '7 d %': -42.68,
  'Owners': 4700,
  'Items': 10000,
  'Category': 'Music',
  'Chain': 'Ethereum',
  'Twitter followers': 26400,
  'Ownership %': 47.0,
  'Volume (USD) in M': 11.01734395,
  'Floor (USD)': 256.7376,
  'Gas Volume (USD) in M': 0.235,
  'Market Share %': 29.96,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'The Orbs by BT',
  '24 hs %': 0.0,
  '7 d %': -8.2,
  'Owners': 1400,
  'Items': 3300,
  'Category': 'Music',
  'Chain': 'Ethereum',
  'Twitter followers': 622700,
  'Ownership %': 42.42424242,
  'Volume (USD) in M': 4.472350654,
  'Floor (USD)': 550.152,
  'Gas Volume (USD) in M': 0.07,
  'Market Share %': 12.16,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'EulerBeats Genesis',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 431,
  'Items': 54,
  'Category': 'Music',
  'Chain': 'Ethereum',
  'Twitter followers': 14100,
  'Ownership %': 798.1481481,
  'Volume (USD) in M': 4.227294614,
  'Floor (USD)': 2017.224,
  'Gas Volume (USD) in M': 0.02155,
  'Market Share %': 11.5,
  'Growth': 'Not interesting',
  'Ownership Status': 'Massive OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Shark',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'EulerBeats Enigma',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 101,
  'Items': 54,
  'Category': 'Music',
  'Chain': 'Ethereum',
  'Twitter followers': 14100,
  'Ownership %': 187.037037,
  'Volume (USD) in M': 3.69025457,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 0.00505,
  'Market Share %': 10.04,
  'Growth': 'Not interesting',
  'Ownership Status': 'Massive OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Medium gas',
  'Market Status': 'Shark',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Audioglyphs',
  '24 hs %': 0.0,
  '7 d %': 15.2,
  'Owners': 2700,
  'Items': 10000,
  'Category': 'Music',
  'Chain': 'Ethereum',
  'Twitter followers': 3920,
  'Ownership %': 27.0,
  'Volume (USD) in M': 2.042659361,
  'Floor (USD)': 550.152,
  'Gas Volume (USD) in M': 0.135,
  'Market Share %': 5.56,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Emerging',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'High gas',
  'Market Status': 'Shark',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Justin Aversano - Twin Flames - Collection of 100 Twins Portraits',
  '24 hs %': 0.0,
  '7 d %': -100.0,
  'Owners': 88,
  'Items': 100,
  'Category': 'Photography',
  'Chain': 'Ethereum',
  'Twitter followers': 78600,
  'Ownership %': 88.0,
  'Volume (USD) in M': 9.496833854,
  'Floor (USD)': 206307.0,
  'Gas Volume (USD) in M': 0.0044,
  'Market Share %': 25.83,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Whale',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Where My Vans Go',
  '24 hs %': -100.0,
  '7 d %': -75.29,
  'Owners': 102,
  'Items': 123,
  'Category': 'Photography',
  'Chain': 'Ethereum',
  'Twitter followers': 119000,
  'Ownership %': 82.92682927,
  'Volume (USD) in M': 6.536355912,
  'Floor (USD)': 82522.8,
  'Gas Volume (USD) in M': 0.0051,
  'Market Share %': 17.78,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Whale',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Women Unite - 10k Assemble',
  '24 hs %': 10.63,
  '7 d %': -48.84,
  'Owners': 1500,
  'Items': 6700,
  'Category': 'Photography',
  'Chain': 'Ethereum',
  'Twitter followers': 9615,
  'Ownership %': 22.3880597,
  'Volume (USD) in M': 1.286695498,
  'Floor (USD)': 513.4752,
  'Gas Volume (USD) in M': 0.075,
  'Market Share %': 3.5,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Emerging',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Shark',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'First Day Out by DrifterShoots',
  '24 hs %': 15.15,
  '7 d %': -53.23,
  'Owners': 6700,
  'Items': 10400,
  'Category': 'Photography',
  'Chain': 'Ethereum',
  'Twitter followers': 119000,
  'Ownership %': 64.42307692,
  'Volume (USD) in M': 0.6920728776,
  'Floor (USD)': 73.3536,
  'Gas Volume (USD) in M': 0.335,
  'Market Share %': 1.88,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Shark',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Editions x Guido',
  '24 hs %': -33.73,
  '7 d %': -11.45,
  'Owners': 10400,
  'Items': 2,
  'Category': 'Photography',
  'Chain': 'Ethereum',
  'Twitter followers': 25800,
  'Ownership %': 520000.0,
  'Volume (USD) in M': 0.662658084,
  'Floor (USD)': 91.692,
  'Gas Volume (USD) in M': 0.52,
  'Market Share %': 1.8,
  'Growth': 'Not interesting',
  'Ownership Status': 'Massive OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Shark',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'The Association',
  '24 hs %': -25.85,
  '7 d %': -3.549,
  'Owners': 15400,
  'Items': 30000,
  'Category': 'Sports',
  'Chain': 'Ethereum',
  'Twitter followers': 27800,
  'Ownership %': 51.33333333,
  'Volume (USD) in M': 10.36433187,
  'Floor (USD)': 36.6768,
  'Gas Volume (USD) in M': 0.77,
  'Market Share %': 28.19,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'F1 Delta Time',
  '24 hs %': 0.0,
  '7 d %': -79.28,
  'Owners': 1800,
  'Items': 40500,
  'Category': 'Sports',
  'Chain': 'Ethereum',
  'Twitter followers': 0,
  'Ownership %': 4.444444444,
  'Volume (USD) in M': 7.70957339,
  'Floor (USD)': 18.3384,
  'Gas Volume (USD) in M': 0.09,
  'Market Share %': 20.97,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Medium gas',
  'Market Status': 'Whale',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Legionfarm Gaming Heroes #1',
  '24 hs %': -100.0,
  '7 d %': 0.0,
  'Owners': 428,
  'Items': 3000,
  'Category': 'Sports',
  'Chain': 'Ethereum',
  'Twitter followers': 9082,
  'Ownership %': 14.26666667,
  'Volume (USD) in M': 6.218129657,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 0.0214,
  'Market Share %': 16.91,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Emerging',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Medium gas',
  'Market Status': 'Whale',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'MLB Champions',
  '24 hs %': 35.0,
  '7 d %': -98.25,
  'Owners': 2700,
  'Items': 249100,
  'Category': 'Sports',
  'Chain': 'Ethereum',
  'Twitter followers': 3994,
  'Ownership %': 1.083902047,
  'Volume (USD) in M': 6.073879802,
  'Floor (USD)': 18.3384,
  'Gas Volume (USD) in M': 0.135,
  'Market Share %': 16.52,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Parallel Alpha',
  '24 hs %': -73.92,
  '7 d %': 100.0,
  'Owners': 45600,
  'Items': 535,
  'Category': 'Trading Cards',
  'Chain': 'Ethereum',
  'Twitter followers': 97200,
  'Ownership %': 8523.364486,
  'Volume (USD) in M': 121.4415244,
  'Floor (USD)': 18.3384,
  'Gas Volume (USD) in M': 2.28,
  'Market Share %': 330.28,
  'Growth': 'Not interesting',
  'Ownership Status': 'Massive OS',
  'Popularity': 'Community',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Not recommended'},
 {'Collection': 'My Curio Cards',
  '24 hs %': -21.4,
  '7 d %': 5.39,
  'Owners': 5000,
  'Items': 30,
  'Category': 'Trading Cards',
  'Chain': 'Ethereum',
  'Twitter followers': 14400,
  'Ownership %': 16666.66667,
  'Volume (USD) in M': 68.85676758,
  'Floor (USD)': 458.46,
  'Gas Volume (USD) in M': 0.25,
  'Market Share %': 187.27,
  'Growth': 'Not interesting',
  'Ownership Status': 'Massive OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Meme Ltd.',
  '24 hs %': 0.0,
  '7 d %': 275.96,
  'Owners': 8400,
  'Items': 522,
  'Category': 'Trading Cards',
  'Chain': 'Ethereum',
  'Twitter followers': 23000,
  'Ownership %': 1609.195402,
  'Volume (USD) in M': 8.808171919,
  'Floor (USD)': 18.3384,
  'Gas Volume (USD) in M': 0.42,
  'Market Share %': 23.96,
  'Growth': 'Not interesting',
  'Ownership Status': 'Massive OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Playing Arts Crypto Edition',
  '24 hs %': -100.0,
  '7 d %': -38.54,
  'Owners': 1500,
  'Items': 7800,
  'Category': 'Trading Cards',
  'Chain': 'Ethereum',
  'Twitter followers': 6501,
  'Ownership %': 19.23076923,
  'Volume (USD) in M': 8.095578372,
  'Floor (USD)': 36.6768,
  'Gas Volume (USD) in M': 0.075,
  'Market Share %': 22.02,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Emerging',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Medium gas',
  'Market Status': 'Whale',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Emblem Vault [Ethereum]',
  '24 hs %': -63.87,
  '7 d %': -67.04,
  'Owners': 5600,
  'Items': 26100,
  'Category': 'Utility',
  'Chain': 'Ethereum',
  'Twitter followers': 5361,
  'Ownership %': 21.4559387,
  'Volume (USD) in M': 61.01293877,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 0.28,
  'Market Share %': 165.93,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Emerging',
  'Accesibility': 'Not interesting',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Metroverse Genesis',
  '24 hs %': 30.3,
  '7 d %': -37.88,
  'Owners': 297,
  'Items': 10000,
  'Category': 'Utility',
  'Chain': 'Ethereum',
  'Twitter followers': 273300,
  'Ownership %': 2.97,
  'Volume (USD) in M': 45.65896666,
  'Floor (USD)': 550.152,
  'Gas Volume (USD) in M': 0.01485,
  'Market Share %': 124.18,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Whale',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Project NANOPASS',
  '24 hs %': -6.89,
  '7 d %': -19.41,
  'Owners': 4000,
  'Items': 5600,
  'Category': 'Utility',
  'Chain': 'Ethereum',
  'Twitter followers': 1780,
  'Ownership %': 71.42857143,
  'Volume (USD) in M': 30.24616496,
  'Floor (USD)': 3392.604,
  'Gas Volume (USD) in M': 0.2,
  'Market Share %': 82.26,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Emerging',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'JRNY Club',
  '24 hs %': 148.77,
  '7 d %': 4.977,
  'Owners': 6200,
  'Items': 10000,
  'Category': 'Utility',
  'Chain': 'Ethereum',
  'Twitter followers': 283000,
  'Ownership %': 62.0,
  'Volume (USD) in M': 27.88837854,
  'Floor (USD)': 1650.456,
  'Gas Volume (USD) in M': 0.31,
  'Market Share %': 75.85,
  'Growth': 'Emerging',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Wolf Game Legacy',
  '24 hs %': 0.0,
  '7 d %': -100.0,
  'Owners': 13,
  'Items': 13800,
  'Category': 'Utility',
  'Chain': 'Ethereum',
  'Twitter followers': 54600,
  'Ownership %': 0.09420289855,
  'Volume (USD) in M': 25.00673738,
  'Floor (USD)': 3392.604,
  'Gas Volume (USD) in M': 0.00065,
  'Market Share %': 68.01,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Whale',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Descentraland',
  '24 hs %': -19.61,
  '7 d %': -20.4,
  'Owners': 7200,
  'Items': 97500,
  'Category': 'Virtual Worlds',
  'Chain': 'Ethereum',
  'Twitter followers': 630200,
  'Ownership %': 7.384615385,
  'Volume (USD) in M': 304.131581,
  'Floor (USD)': 3392.604,
  'Gas Volume (USD) in M': 0.36,
  'Market Share %': 827.13,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Not recommended'},
 {'Collection': 'The Sandbox',
  '24 hs %': -48.37,
  '7 d %': -91.0,
  'Owners': 21800,
  'Items': 142000,
  'Category': 'Virtual Worlds',
  'Chain': 'Ethereum',
  'Twitter followers': 1000000,
  'Ownership %': 15.35211268,
  'Volume (USD) in M': 283.9731315,
  'Floor (USD)': 3099.1896,
  'Gas Volume (USD) in M': 1.09,
  'Market Share %': 772.31,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Not recommended'},
 {'Collection': 'NFT Worlds',
  '24 hs %': -28.69,
  '7 d %': 6.35,
  'Owners': 760,
  'Items': 10000,
  'Category': 'Virtual Worlds',
  'Chain': 'Ethereum',
  'Twitter followers': 142000,
  'Ownership %': 7.6,
  'Volume (USD) in M': 89.00450748,
  'Floor (USD)': 5868.288,
  'Gas Volume (USD) in M': 0.038,
  'Market Share %': 242.06,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Whale',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Decentraland Wearables',
  '24 hs %': 854.27,
  '7 d %': -35.0,
  'Owners': 10700,
  'Items': 71600,
  'Category': 'Virtual Worlds',
  'Chain': 'Ethereum',
  'Twitter followers': 1797,
  'Ownership %': 14.94413408,
  'Volume (USD) in M': 88.88950737,
  'Floor (USD)': 18.3384,
  'Gas Volume (USD) in M': 0.535,
  'Market Share %': 241.75,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Emerging',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Town Star',
  '24 hs %': 5.18,
  '7 d %': -41.6,
  'Owners': 44300,
  'Items': 518,
  'Category': 'Virtual Worlds',
  'Chain': 'Ethereum',
  'Twitter followers': 10700,
  'Ownership %': 8552.123552,
  'Volume (USD) in M': 50.78597985,
  'Floor (USD)': 18.3384,
  'Gas Volume (USD) in M': 2.215,
  'Market Share %': 138.12,
  'Growth': 'Not interesting',
  'Ownership Status': 'Massive OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Phantom Galaxies Planer Genesis Series',
  '24 hs %': 160.54,
  '7 d %': 785.83,
  'Owners': 3700,
  'Items': 7,
  'Category': 'New',
  'Chain': 'Polygon',
  'Twitter followers': 108200,
  'Ownership %': 52857.14286,
  'Volume (USD) in M': 0.1031351616,
  'Floor (USD)': 18.3384,
  'Gas Volume (USD) in M': 0.185,
  'Market Share %': 0.28,
  'Growth': 'Hot - buy now',
  'Ownership Status': 'Massive OS',
  'Popularity': 'Community',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Creadore Universe',
  '24 hs %': 23.3,
  '7 d %': 9.92,
  'Owners': 1600,
  'Items': 1600,
  'Category': 'New',
  'Chain': 'Polygon',
  'Twitter followers': 12500,
  'Ownership %': 100.0,
  'Volume (USD) in M': 0.0686039544,
  'Floor (USD)': 1026.9504,
  'Gas Volume (USD) in M': 0.08,
  'Market Share %': 0.19,
  'Growth': 'Hot - watchlist',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Fish',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'KemonoVerse',
  '24 hs %': 0.0,
  '7 d %': -90.7,
  'Owners': 531,
  'Items': 3300,
  'Category': 'New',
  'Chain': 'Polygon',
  'Twitter followers': 8700,
  'Ownership %': 16.09090909,
  'Volume (USD) in M': 0.0556753824,
  'Floor (USD)': 146.7072,
  'Gas Volume (USD) in M': 0.02655,
  'Market Share %': 0.15,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Medium gas',
  'Market Status': 'Fish',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'The Cornz',
  '24 hs %': -100.0,
  '7 d %': -93.55,
  'Owners': 1000,
  'Items': 15000,
  'Category': 'New',
  'Chain': 'Polygon',
  'Twitter followers': 1330,
  'Ownership %': 6.666666667,
  'Volume (USD) in M': 0.0226295856,
  'Floor (USD)': 18.3384,
  'Gas Volume (USD) in M': 0.05,
  'Market Share %': 0.06,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Medium gas',
  'Market Status': 'Fish',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Adocatty',
  '24 hs %': 0.0,
  '7 d %': -50.89,
  'Owners': 65,
  'Items': 2000,
  'Category': 'New',
  'Chain': 'Polygon',
  'Twitter followers': 0,
  'Ownership %': 3.25,
  'Volume (USD) in M': 0.0167612976,
  'Floor (USD)': 18.3384,
  'Gas Volume (USD) in M': 0.00325,
  'Market Share %': 0.05,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Medium gas',
  'Market Status': 'Fish',
  'Recommendation': 'Not recommended'},
 {'Collection': 'The Martians: Metaverse',
  '24 hs %': -50.19,
  '7 d %': 39.02,
  'Owners': 710,
  'Items': 5000,
  'Category': 'Art',
  'Chain': 'Polygon',
  'Twitter followers': 73800,
  'Ownership %': 14.2,
  'Volume (USD) in M': 3.299756681,
  'Floor (USD)': 1136.9808,
  'Gas Volume (USD) in M': 0.0355,
  'Market Share %': 8.97,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Shark',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'DEFY Genesis Masks',
  '24 hs %': -26.54,
  '7 d %': -26.05,
  'Owners': 4800,
  'Items': 8700,
  'Category': 'Art',
  'Chain': 'Polygon',
  'Twitter followers': 34000,
  'Ownership %': 55.17241379,
  'Volume (USD) in M': 2.058540415,
  'Floor (USD)': 513.4752,
  'Gas Volume (USD) in M': 0.24,
  'Market Share %': 5.6,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'High gas',
  'Market Status': 'Shark',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Artvatars',
  '24 hs %': -100.0,
  '7 d %': -80.22,
  'Owners': 1600,
  'Items': 6700,
  'Category': 'Art',
  'Chain': 'Polygon',
  'Twitter followers': 22200,
  'Ownership %': 23.88059701,
  'Volume (USD) in M': 1.30477716,
  'Floor (USD)': 165.0456,
  'Gas Volume (USD) in M': 0.08,
  'Market Share %': 3.55,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Medium gas',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Chinese Zodiaz Metavase by YassartLabs',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 143,
  'Items': 1000,
  'Category': 'Art',
  'Chain': 'Polygon',
  'Twitter followers': 108,
  'Ownership %': 14.3,
  'Volume (USD) in M': 0.779932152,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 0.00715,
  'Market Share %': 2.12,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Emerging',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Medium gas',
  'Market Status': 'Shark',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Redemption Tokens for Brendan Murphy Physical Art',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 1000,
  'Items': 5,
  'Category': 'Art',
  'Chain': 'Polygon',
  'Twitter followers': 40000,
  'Ownership %': 20000.0,
  'Volume (USD) in M': 0.4628245392,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 0.05,
  'Market Share %': 1.26,
  'Growth': 'Not interesting',
  'Ownership Status': 'Massive OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Medium gas',
  'Market Status': 'Shark',
  'Recommendation': 'Not recommended'},
 {'Collection': 'BCCG',
  '24 hs %': -100.0,
  '7 d %': 55979.5,
  'Owners': 5400,
  'Items': 58,
  'Category': 'Collectibles',
  'Chain': 'Polygon',
  'Twitter followers': 0,
  'Ownership %': 9310.344828,
  'Volume (USD) in M': 7.376566385,
  'Floor (USD)': 18.3384,
  'Gas Volume (USD) in M': 0.27,
  'Market Share %': 20.06,
  'Growth': 'Not interesting',
  'Ownership Status': 'Massive OS',
  'Popularity': 'Not interesting',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Chumbi Valley Official',
  '24 hs %': 149.48,
  '7 d %': 44.07,
  'Owners': 1800,
  'Items': 4100,
  'Category': 'Collectibles',
  'Chain': 'Polygon',
  'Twitter followers': 246300,
  'Ownership %': 43.90243902,
  'Volume (USD) in M': 5.69544858,
  'Floor (USD)': 366.768,
  'Gas Volume (USD) in M': 0.09,
  'Market Share %': 15.49,
  'Growth': 'Hot - buy now',
  'Ownership Status': 'Low OS',
  'Popularity': 'Community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Medium gas',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Ember Sword Land',
  '24 hs %': -85.0,
  '7 d %': 19.0,
  'Owners': 6100,
  'Items': 40000,
  'Category': 'Collectibles',
  'Chain': 'Polygon',
  'Twitter followers': 2685,
  'Ownership %': 15.25,
  'Volume (USD) in M': 5.577844421,
  'Floor (USD)': 183.384,
  'Gas Volume (USD) in M': 0.305,
  'Market Share %': 15.17,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Emerging',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Shark',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'DogeSound Compilation (3PM official)',
  '24 hs %': 0.0,
  '7 d %': -100.0,
  'Owners': 397,
  'Items': 4,
  'Category': 'Music',
  'Chain': 'Polygon',
  'Twitter followers': 2288,
  'Ownership %': 9925.0,
  'Volume (USD) in M': 0.0567023328,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 0.01985,
  'Market Share %': 0.15,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Medium gas',
  'Market Status': 'Fish',
  'Recommendation': 'Not recommended'},
 {'Collection': 'WVRPS Drops',
  '24 hs %': 5864.4,
  '7 d %': 129.0,
  'Owners': 6100,
  'Items': 10,
  'Category': 'Music',
  'Chain': 'Polygon',
  'Twitter followers': 26300,
  'Ownership %': 61000.0,
  'Volume (USD) in M': 0.0137904768,
  'Floor (USD)': 183.384,
  'Gas Volume (USD) in M': 0.305,
  'Market Share %': 0.04,
  'Growth': 'Hot - buy now',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Fish',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'XXXTentacion NFT Collection (Official)',
  '24 hs %': -100.0,
  '7 d %': 136.0,
  'Owners': 2900,
  'Items': 30000,
  'Category': 'Music',
  'Chain': 'Polygon',
  'Twitter followers': 0,
  'Ownership %': 9.666666667,
  'Volume (USD) in M': 0.0036493416,
  'Floor (USD)': 183.384,
  'Gas Volume (USD) in M': 0.145,
  'Market Share %': 0.01,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Fish',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Mint Songs',
  '24 hs %': 0.0,
  '7 d %': 74.0,
  'Owners': 2800,
  'Items': 74600,
  'Category': 'Music',
  'Chain': 'Polygon',
  'Twitter followers': 16100,
  'Ownership %': 3.753351206,
  'Volume (USD) in M': 0.0035026344,
  'Floor (USD)': 183.384,
  'Gas Volume (USD) in M': 0.14,
  'Market Share %': 0.01,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Fish',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Boomboom Monsters',
  '24 hs %': 0.0,
  '7 d %': -93.0,
  'Owners': 38,
  'Items': 111,
  'Category': 'Music',
  'Chain': 'Polygon',
  'Twitter followers': 4600,
  'Ownership %': 34.23423423,
  'Volume (USD) in M': 0.0023473152,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 0.0019,
  'Market Share %': 0.01,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Medium gas',
  'Market Status': 'Fish',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Itadakimasu Man',
  '24 hs %': 0.0,
  '7 d %': -100.0,
  'Owners': 330,
  'Items': 758,
  'Category': 'Photography',
  'Chain': 'Polygon',
  'Twitter followers': 2162,
  'Ownership %': 43.53562005,
  'Volume (USD) in M': 0.037685412,
  'Floor (USD)': 183.384,
  'Gas Volume (USD) in M': 0.0165,
  'Market Share %': 0.1,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Medium gas',
  'Market Status': 'Fish',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'AP Photojournalism NFTs',
  '24 hs %': 0.0,
  '7 d %': -100.0,
  'Owners': 122,
  'Items': 190,
  'Category': 'Photography',
  'Chain': 'Polygon',
  'Twitter followers': 15800000,
  'Ownership %': 64.21052632,
  'Volume (USD) in M': 0.0059416416,
  'Floor (USD)': 73.3536,
  'Gas Volume (USD) in M': 0.0061,
  'Market Share %': 0.02,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Medium gas',
  'Market Status': 'Fish',
  'Recommendation': 'Not recommended'},
 {'Collection': '8 yers of Everydays',
  '24 hs %': -100.0,
  '7 d %': 0.0,
  'Owners': 7,
  'Items': 2400,
  'Category': 'Photography',
  'Chain': 'Polygon',
  'Twitter followers': 0,
  'Ownership %': 0.2916666667,
  'Volume (USD) in M': 0.0006235056,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 0.00035,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Medium gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Foundnon: Artifacts',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 80,
  'Items': 130,
  'Category': 'Photography',
  'Chain': 'Polygon',
  'Twitter followers': 2778,
  'Ownership %': 61.53846154,
  'Volume (USD) in M': 0.0005318136,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 0.004,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Medium gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'The New Days',
  '24 hs %': 0.0,
  '7 d %': -100.0,
  'Owners': 2,
  'Items': 4,
  'Category': 'Photography',
  'Chain': 'Polygon',
  'Twitter followers': 0,
  'Ownership %': 50.0,
  'Volume (USD) in M': 0.0005318136,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 0.0001,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Medium gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'ZED RUN',
  '24 hs %': -30.24,
  '7 d %': 122.47,
  'Owners': 26700,
  'Items': 200100,
  'Category': 'Sports',
  'Chain': 'Polygon',
  'Twitter followers': 69500,
  'Ownership %': 13.34332834,
  'Volume (USD) in M': 1.741304434,
  'Floor (USD)': 18.3384,
  'Gas Volume (USD) in M': 1.335,
  'Market Share %': 4.74,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Community',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Shark',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'REVV Racing',
  '24 hs %': 93.31,
  '7 d %': 43.29,
  'Owners': 59400,
  'Items': 169200,
  'Category': 'Sports',
  'Chain': 'Polygon',
  'Twitter followers': 157200,
  'Ownership %': 35.10638298,
  'Volume (USD) in M': 0.5957596008,
  'Floor (USD)': 18.3384,
  'Gas Volume (USD) in M': 2.97,
  'Market Share %': 1.62,
  'Growth': 'Hot - buy now',
  'Ownership Status': 'Low OS',
  'Popularity': 'Community',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'MetaSoccer Youth Scouts',
  '24 hs %': 0.0,
  '7 d %': -80.21,
  'Owners': 1400,
  'Items': 8500,
  'Category': 'Sports',
  'Chain': 'Polygon',
  'Twitter followers': 0,
  'Ownership %': 16.47058824,
  'Volume (USD) in M': 0.3896543232,
  'Floor (USD)': 36.6768,
  'Gas Volume (USD) in M': 0.07,
  'Market Share %': 1.06,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Not interesting',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Medium gas',
  'Market Status': 'Shark',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Friday Night Punks',
  '24 hs %': -4.26,
  '7 d %': -2.97,
  'Owners': 657,
  'Items': 321,
  'Category': 'Sports',
  'Chain': 'Polygon',
  'Twitter followers': 1700,
  'Ownership %': 204.6728972,
  'Volume (USD) in M': 0.0877675824,
  'Floor (USD)': 55.0152,
  'Gas Volume (USD) in M': 0.03285,
  'Market Share %': 0.24,
  'Growth': 'Not interesting',
  'Ownership Status': 'Massive OS',
  'Popularity': 'Emerging',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Medium gas',
  'Market Status': 'Shark',
  'Recommendation': 'Not recommended'},
 {'Collection': 'BCCG',
  '24 hs %': -100.0,
  '7 d %': 55979.5,
  'Owners': 5400,
  'Items': 58,
  'Category': 'Trading Cards',
  'Chain': 'Polygon',
  'Twitter followers': 0,
  'Ownership %': 9310.344828,
  'Volume (USD) in M': 7.376566385,
  'Floor (USD)': 18.3384,
  'Gas Volume (USD) in M': 0.27,
  'Market Share %': 20.06,
  'Growth': 'Not interesting',
  'Ownership Status': 'Massive OS',
  'Popularity': 'Not interesting',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Not recommended'},
 {'Collection': "Ethernity's Master Collection",
  '24 hs %': 5060.6,
  '7 d %': -43.84,
  'Owners': 8200,
  'Items': 22100,
  'Category': 'Trading Cards',
  'Chain': 'Polygon',
  'Twitter followers': 127100,
  'Ownership %': 37.1040724,
  'Volume (USD) in M': 2.261308104,
  'Floor (USD)': 18.3384,
  'Gas Volume (USD) in M': 0.41,
  'Market Share %': 6.15,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Community',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Shark',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Marble Cards',
  '24 hs %': 0.0,
  '7 d %': -100.0,
  'Owners': 10200,
  'Items': 256900,
  'Category': 'Trading Cards',
  'Chain': 'Polygon',
  'Twitter followers': 27500,
  'Ownership %': 3.970416504,
  'Volume (USD) in M': 1.134046656,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 0.51,
  'Market Share %': 3.08,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Not interesting',
  'Gas Status': 'High gas',
  'Market Status': 'Shark',
  'Recommendation': 'Not recommended'},
 {'Collection': 'PolkaFantasy',
  '24 hs %': -100.0,
  '7 d %': 2589.0,
  'Owners': 1300,
  'Items': 6700,
  'Category': 'Trading Cards',
  'Chain': 'Polygon',
  'Twitter followers': 48800,
  'Ownership %': 19.40298507,
  'Volume (USD) in M': 0.4164283872,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 0.065,
  'Market Share %': 1.13,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Community',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Medium gas',
  'Market Status': 'Shark',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Decentral Games ICE Poker',
  '24 hs %': 33.37,
  '7 d %': -3.639,
  'Owners': 4100,
  'Items': 34200,
  'Category': 'Utility',
  'Chain': 'Polygon',
  'Twitter followers': 101500,
  'Ownership %': 11.98830409,
  'Volume (USD) in M': 22.18586967,
  'Floor (USD)': 605.1672,
  'Gas Volume (USD) in M': 0.205,
  'Market Share %': 60.34,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Chicken Derby',
  '24 hs %': -48.62,
  '7 d %': -2.807,
  'Owners': 6000,
  'Items': 33300,
  'Category': 'Utility',
  'Chain': 'Polygon',
  'Twitter followers': 25000,
  'Ownership %': 18.01801802,
  'Volume (USD) in M': 7.37535605,
  'Floor (USD)': 36.6768,
  'Gas Volume (USD) in M': 0.3,
  'Market Share %': 20.06,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Whale',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Crypto Raiders Characters',
  '24 hs %': 53.9,
  '7 d %': 63.98,
  'Owners': 4500,
  'Items': 68900,
  'Category': 'Utility',
  'Chain': 'Polygon',
  'Twitter followers': 29000,
  'Ownership %': 6.531204644,
  'Volume (USD) in M': 4.195569182,
  'Floor (USD)': 18.3384,
  'Gas Volume (USD) in M': 0.225,
  'Market Share %': 11.41,
  'Growth': 'Hot - buy now',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Genesis Curry Flow',
  '24 hs %': 4063.0,
  '7 d %': 45.87,
  'Owners': 2200,
  'Items': 5,
  'Category': 'Utility',
  'Chain': 'Polygon',
  'Twitter followers': 484000,
  'Ownership %': 44000.0,
  'Volume (USD) in M': 3.990050734,
  'Floor (USD)': 183.384,
  'Gas Volume (USD) in M': 0.11,
  'Market Share %': 10.85,
  'Growth': 'Hot - buy now',
  'Ownership Status': 'Massive OS',
  'Popularity': 'Community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Medium gas',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'The Red Village Champions',
  '24 hs %': -12.3,
  '7 d %': -24.19,
  'Owners': 2000,
  'Items': 11000,
  'Category': 'Utility',
  'Chain': 'Polygon',
  'Twitter followers': 19200,
  'Ownership %': 18.18181818,
  'Volume (USD) in M': 3.836705033,
  'Floor (USD)': 110.0304,
  'Gas Volume (USD) in M': 0.1,
  'Market Share %': 10.43,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Medium gas',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Ember Sword Land',
  '24 hs %': -85.08,
  '7 d %': 19.0,
  'Owners': 6100,
  'Items': 40000,
  'Category': 'Virtual Worlds',
  'Chain': 'Polygon',
  'Twitter followers': 87500,
  'Ownership %': 15.25,
  'Volume (USD) in M': 5.577844421,
  'Floor (USD)': 183.384,
  'Gas Volume (USD) in M': 0.305,
  'Market Share %': 15.17,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'High gas',
  'Market Status': 'Shark',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Mona Spaces (Polygon)',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 82,
  'Items': 123,
  'Category': 'Virtual Worlds',
  'Chain': 'Polygon',
  'Twitter followers': 16800,
  'Ownership %': 66.66666667,
  'Volume (USD) in M': 0.0445989888,
  'Floor (USD)': 183.384,
  'Gas Volume (USD) in M': 0.0041,
  'Market Share %': 0.12,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Medium gas',
  'Market Status': 'Fish',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Cyber Destinations Curated',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 1,
  'Items': 1,
  'Category': 'Virtual Worlds',
  'Chain': 'Polygon',
  'Twitter followers': 0,
  'Ownership %': 100.0,
  'Volume (USD) in M': 0.0233997984,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 5e-05,
  'Market Share %': 0.06,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Low gas',
  'Market Status': 'Fish',
  'Recommendation': 'Not recommended'},
 {'Collection': 'NFT Moon Metaverse (Polygon)',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 163,
  'Items': 286,
  'Category': 'Virtual Worlds',
  'Chain': 'Polygon',
  'Twitter followers': 50800,
  'Ownership %': 56.99300699,
  'Volume (USD) in M': 0.0024573456,
  'Floor (USD)': 1100.304,
  'Gas Volume (USD) in M': 0.00815,
  'Market Share %': 0.01,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Fish',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Shen V4',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 163,
  'Items': 10,
  'Category': 'Virtual Worlds',
  'Chain': 'Polygon',
  'Twitter followers': 0,
  'Ownership %': 1630.0,
  'Volume (USD) in M': 0.0,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 0.00815,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Medium gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Cardboard Citizens',
  '24 hs %': -27.42,
  '7 d %': -63.2,
  'Owners': 3100,
  'Items': 6800,
  'Category': 'New',
  'Chain': 'Solana',
  'Twitter followers': 14400,
  'Ownership %': 45.58823529,
  'Volume (USD) in M': 3.1788,
  'Floor (USD)': 220.5,
  'Gas Volume (USD) in M': 3.13e-06,
  'Market Share %': 8.65,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Shark',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Balloonsville',
  '24 hs %': -32.44,
  '7 d %': -15.88,
  'Owners': 1400,
  'Items': 5000,
  'Category': 'New',
  'Chain': 'Solana',
  'Twitter followers': 16600,
  'Ownership %': 28.0,
  'Volume (USD) in M': 2.634165,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 1.41e-06,
  'Market Share %': 7.16,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Low gas',
  'Market Status': 'Shark',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'The Bridged bt The Fracture',
  '24 hs %': -19.79,
  '7 d %': -60.77,
  'Owners': 4300,
  'Items': 9800,
  'Category': 'New',
  'Chain': 'Solana',
  'Twitter followers': 0,
  'Ownership %': 43.87755102,
  'Volume (USD) in M': 2.505645,
  'Floor (USD)': 180.0,
  'Gas Volume (USD) in M': 4.35e-06,
  'Market Share %': 6.81,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Not interesting',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Shark',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Bunnies N Homies Club',
  '24 hs %': -39.57,
  '7 d %': 0.0,
  'Owners': 4100,
  'Items': 7600,
  'Category': 'New',
  'Chain': 'Solana',
  'Twitter followers': 89700,
  'Ownership %': 53.94736842,
  'Volume (USD) in M': 2.03697,
  'Floor (USD)': 179.1,
  'Gas Volume (USD) in M': 4.14e-06,
  'Market Share %': 5.54,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Okay Bears',
  '24 hs %': -73.0,
  '7 d %': -68.4,
  'Owners': 5400,
  'Items': 10000,
  'Category': 'Art',
  'Chain': 'Solana',
  'Twitter followers': 150000,
  'Ownership %': 54.0,
  'Volume (USD) in M': 73.47996,
  'Floor (USD)': 7605.0,
  'Gas Volume (USD) in M': 5.46e-06,
  'Market Share %': 199.84,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Low gas',
  'Market Status': 'Whale',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'ASTRALS',
  '24 hs %': -5.0,
  '7 d %': 0.93,
  'Owners': 3600,
  'Items': 10000,
  'Category': 'Art',
  'Chain': 'Solana',
  'Twitter followers': 35800,
  'Ownership %': 36.0,
  'Volume (USD) in M': 6.34347,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 3.64e-06,
  'Market Share %': 17.25,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Low gas',
  'Market Status': 'Whale',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'SOLgods',
  '24 hs %': -18.91,
  '7 d %': -5.99,
  'Owners': 1000,
  'Items': 670,
  'Category': 'Art',
  'Chain': 'Solana',
  'Twitter followers': 39100,
  'Ownership %': 149.2537313,
  'Volume (USD) in M': 4.968765,
  'Floor (USD)': 2430.0,
  'Gas Volume (USD) in M': 1.01e-06,
  'Market Share %': 13.51,
  'Growth': 'Not interesting',
  'Ownership Status': 'Massive OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Low gas',
  'Market Status': 'Shark',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'MOUS IN DA HOUS',
  '24 hs %': -15.6,
  '7 d %': -68.81,
  'Owners': 750,
  'Items': 4400,
  'Category': 'Art',
  'Chain': 'Solana',
  'Twitter followers': 27300,
  'Ownership %': 17.04545455,
  'Volume (USD) in M': 4.82013,
  'Floor (USD)': 283.5,
  'Gas Volume (USD) in M': 7.58e-07,
  'Market Share %': 13.11,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Not interesting',
  'Market Status': 'Shark',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'DeGods',
  '24 hs %': -42.67,
  '7 d %': -16.9,
  'Owners': 4300,
  'Items': 10000,
  'Category': 'Collectibles',
  'Chain': 'Solana',
  'Twitter followers': 10500,
  'Ownership %': 43.0,
  'Volume (USD) in M': 24.38901,
  'Floor (USD)': 18824.85,
  'Gas Volume (USD) in M': 4.35e-06,
  'Market Share %': 66.33,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Low gas',
  'Market Status': 'Whale',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Cets on Creck',
  '24 hs %': -67.14,
  '7 d %': -16.35,
  'Owners': 4100,
  'Items': 7000,
  'Category': 'Collectibles',
  'Chain': 'Solana',
  'Twitter followers': 44200,
  'Ownership %': 58.57142857,
  'Volume (USD) in M': 12.980025,
  'Floor (USD)': 2875.5,
  'Gas Volume (USD) in M': 4.14e-06,
  'Market Share %': 35.3,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Low gas',
  'Market Status': 'Whale',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'TombStoned High Society',
  '24 hs %': -35.04,
  '7 d %': 26.37,
  'Owners': 893,
  'Items': 6600,
  'Category': 'Collectibles',
  'Chain': 'Solana',
  'Twitter followers': 61500,
  'Ownership %': 13.53030303,
  'Volume (USD) in M': 6.567885,
  'Floor (USD)': 652.5,
  'Gas Volume (USD) in M': 9.03e-07,
  'Market Share %': 17.86,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Low gas',
  'Market Status': 'Whale',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Degenerate Ape Academy',
  '24 hs %': -29.91,
  '7 d %': -25.91,
  'Owners': 4300,
  'Items': 10000,
  'Category': 'Collectibles',
  'Chain': 'Solana',
  'Twitter followers': 111111,
  'Ownership %': 43.0,
  'Volume (USD) in M': 6.505065,
  'Floor (USD)': 2790.0,
  'Gas Volume (USD) in M': 4.35e-06,
  'Market Share %': 17.69,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Low gas',
  'Market Status': 'Whale',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Space Runners',
  '24 hs %': -100.0,
  '7 d %': -88.78,
  'Owners': 5100,
  'Items': 9800,
  'Category': 'Collectibles',
  'Chain': 'Solana',
  'Twitter followers': 0,
  'Ownership %': 52.04081633,
  'Volume (USD) in M': 5.750685,
  'Floor (USD)': 450.0,
  'Gas Volume (USD) in M': 5.15e-06,
  'Market Share %': 15.64,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Not interesting',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Low gas',
  'Market Status': 'Shark',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'PixelBands',
  '24 hs %': 7820.0,
  '7 d %': 122.54,
  'Owners': 1200,
  'Items': 4400,
  'Category': 'Music',
  'Chain': 'Solana',
  'Twitter followers': 16000,
  'Ownership %': 27.27272727,
  'Volume (USD) in M': 0.63749385,
  'Floor (USD)': 27.9,
  'Gas Volume (USD) in M': 1.21e-06,
  'Market Share %': 1.73,
  'Growth': 'Hot - buy now',
  'Ownership Status': 'Low OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'SVPLY CHVN Male Robots',
  '24 hs %': 1423.8,
  '7 d %': -79.77,
  'Owners': 889,
  'Items': 2100,
  'Category': 'Music',
  'Chain': 'Solana',
  'Twitter followers': 3253,
  'Ownership %': 42.33333333,
  'Volume (USD) in M': 0.2213532,
  'Floor (USD)': 135.0,
  'Gas Volume (USD) in M': 8.99e-07,
  'Market Share %': 0.6,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Emerging',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'NETGALA',
  '24 hs %': 0.0,
  '7 d %': 100.0,
  'Owners': 761,
  'Items': 2500,
  'Category': 'Music',
  'Chain': 'Solana',
  'Twitter followers': 10700,
  'Ownership %': 30.44,
  'Volume (USD) in M': 0.07137495,
  'Floor (USD)': 33.3,
  'Gas Volume (USD) in M': 7.69e-07,
  'Market Share %': 0.19,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Not interesting',
  'Market Status': 'Fish',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Culture Kids',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 5,
  'Items': 5,
  'Category': 'Music',
  'Chain': 'Solana',
  'Twitter followers': 3332,
  'Ownership %': 100.0,
  'Volume (USD) in M': 0.0,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 5.05e-09,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Not interesting',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'ONEUM',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 0,
  'Items': 0,
  'Category': 'Music',
  'Chain': 'Solana',
  'Twitter followers': 0,
  'Ownership %': 0.0,
  'Volume (USD) in M': 0.0,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 0.0,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Not interesting',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Sol Potato NFT',
  '24 hs %': 0.0,
  '7 d %': -32.02,
  'Owners': 115,
  'Items': 443,
  'Category': 'Photography',
  'Chain': 'Solana',
  'Twitter followers': 295,
  'Ownership %': 25.95936795,
  'Volume (USD) in M': 0.00326745,
  'Floor (USD)': 54.0,
  'Gas Volume (USD) in M': 1.16e-07,
  'Market Share %': 0.01,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Not interesting',
  'Market Status': 'Fish',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Celebrating the Wins',
  '24 hs %': -100.0,
  '7 d %': 2711.9,
  'Owners': 391,
  'Items': 2000,
  'Category': 'Photography',
  'Chain': 'Solana',
  'Twitter followers': 0,
  'Ownership %': 19.55,
  'Volume (USD) in M': 0.0021645,
  'Floor (USD)': 33.75,
  'Gas Volume (USD) in M': 3.95e-07,
  'Market Share %': 0.01,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Not interesting',
  'Market Status': 'Fish',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Shooting for the Gold',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 31,
  'Items': 122,
  'Category': 'Photography',
  'Chain': 'Solana',
  'Twitter followers': 0,
  'Ownership %': 25.40983607,
  'Volume (USD) in M': 0.0001269,
  'Floor (USD)': 45.0,
  'Gas Volume (USD) in M': 3.13e-08,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Not interesting',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Aerial Isolation',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 12,
  'Items': 12,
  'Category': 'Photography',
  'Chain': 'Solana',
  'Twitter followers': 0,
  'Ownership %': 100.0,
  'Volume (USD) in M': 0.0,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 1.21e-08,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Not interesting',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'VaranasiMornings',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 2,
  'Items': 9,
  'Category': 'Photography',
  'Chain': 'Solana',
  'Twitter followers': 0,
  'Ownership %': 22.22222222,
  'Volume (USD) in M': 0.0,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 2.02e-09,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Not interesting',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Photo Finish Live: PFP Collection',
  '24 hs %': 192.82,
  '7 d %': 21.68,
  'Owners': 2100,
  'Items': 15000,
  'Category': 'Sports',
  'Chain': 'Solana',
  'Twitter followers': 15900,
  'Ownership %': 14.0,
  'Volume (USD) in M': 2.2761,
  'Floor (USD)': 220.5,
  'Gas Volume (USD) in M': 2.12e-06,
  'Market Share %': 6.19,
  'Growth': 'Hot - buy now',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Blackasset Legends',
  '24 hs %': 90.81,
  '7 d %': 101.27,
  'Owners': 684,
  'Items': 1700,
  'Category': 'Sports',
  'Chain': 'Solana',
  'Twitter followers': 0,
  'Ownership %': 40.23529412,
  'Volume (USD) in M': 0.313605,
  'Floor (USD)': 135.0,
  'Gas Volume (USD) in M': 6.91e-07,
  'Market Share %': 0.85,
  'Growth': 'Hot - buy now',
  'Ownership Status': 'Low OS',
  'Popularity': 'Not interesting',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Not interesting',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'VBA Season0 Pack',
  '24 hs %': 218.08,
  '7 d %': 59.77,
  'Owners': 146,
  'Items': 1700,
  'Category': 'Sports',
  'Chain': 'Solana',
  'Twitter followers': 9304,
  'Ownership %': 8.588235294,
  'Volume (USD) in M': 0.16893,
  'Floor (USD)': 61.2,
  'Gas Volume (USD) in M': 1.48e-07,
  'Market Share %': 0.46,
  'Growth': 'Hot - buy now',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Emerging',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Not interesting',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': '6 RINGDS',
  '24 hs %': 0.0,
  '7 d %': 161.17,
  'Owners': 146,
  'Items': 176,
  'Category': 'Sports',
  'Chain': 'Solana',
  'Twitter followers': 0,
  'Ownership %': 82.95454545,
  'Volume (USD) in M': 0.039375,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 1.48e-07,
  'Market Share %': 0.11,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Not interesting',
  'Market Status': 'Fish',
  'Recommendation': 'Not recommended'},
 {'Collection': 'VBA PLayers',
  '24 hs %': 53.59,
  '7 d %': 16.62,
  'Owners': 581,
  'Items': 11700,
  'Category': 'Sports',
  'Chain': 'Solana',
  'Twitter followers': 9304,
  'Ownership %': 4.965811966,
  'Volume (USD) in M': 0.038925,
  'Floor (USD)': 12.15,
  'Gas Volume (USD) in M': 5.87e-07,
  'Market Share %': 0.11,
  'Growth': 'Hot - buy now',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Not interesting',
  'Market Status': 'Fish',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'DAGs - Evolved Collection',
  '24 hs %': -100.0,
  '7 d %': 62.59,
  'Owners': 819,
  'Items': 11300,
  'Category': 'Trading Cards',
  'Chain': 'Solana',
  'Twitter followers': 0,
  'Ownership %': 7.247787611,
  'Volume (USD) in M': 0.080685,
  'Floor (USD)': 40.5,
  'Gas Volume (USD) in M': 8.28e-07,
  'Market Share %': 0.22,
  'Growth': 'Not interesting',
  'Ownership Status': 'Very low OS',
  'Popularity': 'Not interesting',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Not interesting',
  'Market Status': 'Shark',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Aces NFT',
  '24 hs %': 0.0,
  '7 d %': -50.87,
  'Owners': 898,
  'Items': 5400,
  'Category': 'Trading Cards',
  'Chain': 'Solana',
  'Twitter followers': 41300,
  'Ownership %': 16.62962963,
  'Volume (USD) in M': 0.03492,
  'Floor (USD)': 22.5,
  'Gas Volume (USD) in M': 9.08e-07,
  'Market Share %': 0.09,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Fish',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Solaxy Metaverse',
  '24 hs %': 46.58,
  '7 d %': -71.92,
  'Owners': 494,
  'Items': 1000,
  'Category': 'Trading Cards',
  'Chain': 'Solana',
  'Twitter followers': 10300,
  'Ownership %': 49.4,
  'Volume (USD) in M': 0.02907,
  'Floor (USD)': 89.55,
  'Gas Volume (USD) in M': 4.99e-07,
  'Market Share %': 0.08,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Not interesting',
  'Market Status': 'Fish',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Secret Space Society: OG Club Card',
  '24 hs %': 47.8,
  '7 d %': 10524.8,
  'Owners': 197,
  'Items': 333,
  'Category': 'Trading Cards',
  'Chain': 'Solana',
  'Twitter followers': 5620,
  'Ownership %': 59.15915916,
  'Volume (USD) in M': 0.01107,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 1.99e-07,
  'Market Share %': 0.03,
  'Growth': 'Hot - buy now',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Not interesting',
  'Market Status': 'Fish',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'SHIZOKU',
  '24 hs %': 49.33,
  '7 d %': 0.0,
  'Owners': 150,
  'Items': 1100,
  'Category': 'Trading Cards',
  'Chain': 'Solana',
  'Twitter followers': 3864,
  'Ownership %': 13.63636364,
  'Volume (USD) in M': 0.00531,
  'Floor (USD)': 19.8,
  'Gas Volume (USD) in M': 1.52e-07,
  'Market Share %': 0.01,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Not interesting',
  'Market Status': 'Fish',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Shadowy Super Coder',
  '24 hs %': 5925.4,
  '7 d %': 6.12,
  'Owners': 148,
  'Items': 10000,
  'Category': 'Utility',
  'Chain': 'Solana',
  'Twitter followers': 41800,
  'Ownership %': 1.48,
  'Volume (USD) in M': 10.50147,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 1.5e-07,
  'Market Share %': 28.56,
  'Growth': 'Hot - watchlist',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Not interesting',
  'Market Status': 'Whale',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Blocksmith Labs',
  '24 hs %': -35.06,
  '7 d %': 4.55,
  'Owners': 2800,
  'Items': 4400,
  'Category': 'Utility',
  'Chain': 'Solana',
  'Twitter followers': 49900,
  'Ownership %': 63.63636364,
  'Volume (USD) in M': 7.47819,
  'Floor (USD)': 10125.0,
  'Gas Volume (USD) in M': 2.83e-06,
  'Market Share %': 20.34,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Low gas',
  'Market Status': 'Whale',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Stoned Ape Crew',
  '24 hs %': 246.0,
  '7 d %': 11.84,
  'Owners': 4100,
  'Items': 4200,
  'Category': 'Utility',
  'Chain': 'Solana',
  'Twitter followers': 67200,
  'Ownership %': 97.61904762,
  'Volume (USD) in M': 5.97015,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 4.14e-06,
  'Market Share %': 16.24,
  'Growth': 'Hot - buy now',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Community',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Low gas',
  'Market Status': 'Whale',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Famous Fox Federation',
  '24 hs %': -17.63,
  '7 d %': -46.2,
  'Owners': 4100,
  'Items': 7800,
  'Category': 'Utility',
  'Chain': 'Solana',
  'Twitter followers': 43300,
  'Ownership %': 52.56410256,
  'Volume (USD) in M': 5.828265,
  'Floor (USD)': 2236.5,
  'Gas Volume (USD) in M': 4.14e-06,
  'Market Share %': 15.85,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Low gas',
  'Market Status': 'Shark',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Dazed Ducks',
  '24 hs %': -20.62,
  '7 d %': -65.42,
  'Owners': 3500,
  'Items': 10000,
  'Category': 'Utility',
  'Chain': 'Solana',
  'Twitter followers': 23600,
  'Ownership %': 35.0,
  'Volume (USD) in M': 4.58793,
  'Floor (USD)': 450.0,
  'Gas Volume (USD) in M': 3.54e-06,
  'Market Share %': 12.48,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Low gas',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Portals',
  '24 hs %': 70.48,
  '7 d %': -12.32,
  'Owners': 2900,
  'Items': 5000,
  'Category': 'Virtual Worlds',
  'Chain': 'Solana',
  'Twitter followers': 51500,
  'Ownership %': 58.0,
  'Volume (USD) in M': 9.192375,
  'Floor (USD)': 2024.55,
  'Gas Volume (USD) in M': 2.93e-06,
  'Market Share %': 25.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Low gas',
  'Market Status': 'Whale',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'The Suites',
  '24 hs %': -4.04,
  '7 d %': -43.88,
  'Owners': 2700,
  'Items': 4900,
  'Category': 'Virtual Worlds',
  'Chain': 'Solana',
  'Twitter followers': 21400,
  'Ownership %': 55.10204082,
  'Volume (USD) in M': 4.630725,
  'Floor (USD)': 441.0,
  'Gas Volume (USD) in M': 2.73e-06,
  'Market Share %': 12.59,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Low gas',
  'Market Status': 'Shark',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Enviro',
  '24 hs %': -12.61,
  '7 d %': -18.45,
  'Owners': 3700,
  'Items': 14000,
  'Category': 'Virtual Worlds',
  'Chain': 'Solana',
  'Twitter followers': 21000,
  'Ownership %': 26.42857143,
  'Volume (USD) in M': 4.32099,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 3.74e-06,
  'Market Share %': 11.75,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Potential community',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Low gas',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'LUX | Real Estate',
  '24 hs %': 32366.7,
  '7 d %': -20.26,
  'Owners': 2600,
  'Items': 5000,
  'Category': 'Virtual Worlds',
  'Chain': 'Solana',
  'Twitter followers': 90300,
  'Ownership %': 52.0,
  'Volume (USD) in M': 4.18491,
  'Floor (USD)': 218.7,
  'Gas Volume (USD) in M': 2.63e-06,
  'Market Share %': 11.38,
  'Growth': 'Not interesting',
  'Ownership Status': 'Medium OS',
  'Popularity': 'Community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Shark',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Boryoku Dragonz',
  '24 hs %': 0.0,
  '7 d %': -72.32,
  'Owners': 548,
  'Items': 1100,
  'Category': 'Virtual Worlds',
  'Chain': 'Solana',
  'Twitter followers': 70000,
  'Ownership %': 49.81818182,
  'Volume (USD) in M': 4.013505,
  'Floor (USD)': 19980.0,
  'Gas Volume (USD) in M': 5.54e-07,
  'Market Share %': 10.92,
  'Growth': 'Not interesting',
  'Ownership Status': 'Low OS',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Not interesting',
  'Market Status': 'Shark',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'KLAYDICE GENESIS-OFFICIAL',
  '24 hs %': -1.2,
  '7 d %': -41.69,
  'Owners': 2000,
  'Items': 3800,
  'Category': 'New',
  'Chain': 'Klaytn',
  'Twitter followers': 74200,
  'Ownership %': 52.63157895,
  'Volume (USD) in M': 0.000848,
  'Floor (USD)': 592.752,
  'Gas Volume (USD) in M': 0.000126,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'CHANGEVERSE',
  '24 hs %': 0.0,
  '7 d %': -100.0,
  'Owners': 3000,
  'Items': 6000,
  'Category': 'New',
  'Chain': 'Klaytn',
  'Twitter followers': 1271,
  'Ownership %': 50.0,
  'Volume (USD) in M': 0.001272,
  'Floor (USD)': 4028.0,
  'Gas Volume (USD) in M': 0.000189,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Waterbomb League Official',
  '24 hs %': -53.41,
  '7 d %': -30.53,
  'Owners': 644,
  'Items': 2800,
  'Category': 'New',
  'Chain': 'Klaytn',
  'Twitter followers': 2421,
  'Ownership %': 23.0,
  'Volume (USD) in M': 0.000273056,
  'Floor (USD)': 71.656,
  'Gas Volume (USD) in M': 4.06e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Hyundai E&C 75th Anniversary NFT',
  '24 hs %': -68.93,
  '7 d %': 0.0,
  'Owners': 557,
  'Items': 750,
  'Category': 'New',
  'Chain': 'Klaytn',
  'Twitter followers': 0,
  'Ownership %': 74.26666667,
  'Volume (USD) in M': 0.000236168,
  'Floor (USD)': 228.536,
  'Gas Volume (USD) in M': 3.51e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'KEROZ LAND MINT PASS',
  '24 hs %': 0.0,
  '7 d %': -37.39,
  'Owners': 691,
  'Items': 3600,
  'Category': 'New',
  'Chain': 'Klaytn',
  'Twitter followers': 13900,
  'Ownership %': 19.19444444,
  'Volume (USD) in M': 0.000292984,
  'Floor (USD)': 146.28,
  'Gas Volume (USD) in M': 4.35e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'META CATS V1',
  '24 hs %': 40.34,
  '7 d %': 5.56,
  'Owners': 1300,
  'Items': 10000,
  'Category': 'Art',
  'Chain': 'Klaytn',
  'Twitter followers': 10200,
  'Ownership %': 13.0,
  'Volume (USD) in M': 0.0005512,
  'Floor (USD)': 12.72,
  'Gas Volume (USD) in M': 8.19e-05,
  'Market Share %': 0.0,
  'Growth': 'Hot - watchlist',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'renaissance-nft',
  '24 hs %': 0.0,
  '7 d %': -70.41,
  'Owners': 715,
  'Items': 3100,
  'Category': 'Art',
  'Chain': 'Klaytn',
  'Twitter followers': 1775,
  'Ownership %': 23.06451613,
  'Volume (USD) in M': 0.00030316,
  'Floor (USD)': 189.952,
  'Gas Volume (USD) in M': 4.5e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'CYE ChuchuCAT V0',
  '24 hs %': 0.0,
  '7 d %': -54.56,
  'Owners': 1000,
  'Items': 3500,
  'Category': 'Art',
  'Chain': 'Klaytn',
  'Twitter followers': 7364,
  'Ownership %': 28.57142857,
  'Volume (USD) in M': 0.000424,
  'Floor (USD)': 67.84,
  'Gas Volume (USD) in M': 6.3e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'KlayDogesFriend',
  '24 hs %': 0.0,
  '7 d %': -100.0,
  'Owners': 1100,
  'Items': 4100,
  'Category': 'Art',
  'Chain': 'Klaytn',
  'Twitter followers': 11800,
  'Ownership %': 26.82926829,
  'Volume (USD) in M': 0.0004664,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 6.93e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Project Spoon DAO',
  '24 hs %': 0.0,
  '7 d %': 109.5,
  'Owners': 1300,
  'Items': 10000,
  'Category': 'Art',
  'Chain': 'Klaytn',
  'Twitter followers': 4629,
  'Ownership %': 13.0,
  'Volume (USD) in M': 0.0005512,
  'Floor (USD)': 19.08,
  'Gas Volume (USD) in M': 8.19e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'THE META KONGZ KLAYTN',
  '24 hs %': -55.03,
  '7 d %': -10.07,
  'Owners': 2000,
  'Items': 6200,
  'Category': 'Collectibles',
  'Chain': 'Klaytn',
  'Twitter followers': 81800,
  'Ownership %': 32.25806452,
  'Volume (USD) in M': 0.000848,
  'Floor (USD)': 4960.8,
  'Gas Volume (USD) in M': 0.000126,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Meta Toy DragonZ',
  '24 hs %': 148.47,
  '7 d %': 7.42,
  'Owners': 2800,
  'Items': 9800,
  'Category': 'Collectibles',
  'Chain': 'Klaytn',
  'Twitter followers': 16800,
  'Ownership %': 28.57142857,
  'Volume (USD) in M': 0.0011872,
  'Floor (USD)': 747.512,
  'Gas Volume (USD) in M': 0.0001764,
  'Market Share %': 0.0,
  'Growth': 'Hot - watchlist',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Highly recommended'},
 {'Collection': 'Mutant Kongz & G.rilla Official',
  '24 hs %': -28.35,
  '7 d %': 6.12,
  'Owners': 6100,
  'Items': 19500,
  'Category': 'Collectibles',
  'Chain': 'Klaytn',
  'Twitter followers': 11300,
  'Ownership %': 31.28205128,
  'Volume (USD) in M': 0.0025864,
  'Floor (USD)': 368.88,
  'Gas Volume (USD) in M': 0.0003843,
  'Market Share %': 0.01,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Medium gas',
  'Market Status': 'Fish',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'DSC | DIGITAL IDENTITY',
  '24 hs %': -100.0,
  '7 d %': 20.0,
  'Owners': 1800,
  'Items': 10000,
  'Category': 'Collectibles',
  'Chain': 'Klaytn',
  'Twitter followers': 17200,
  'Ownership %': 18.0,
  'Volume (USD) in M': 0.0007632,
  'Floor (USD)': 118.72,
  'Gas Volume (USD) in M': 0.0001134,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Medium gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Meta Adventure, frozen',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 3400,
  'Items': 10000,
  'Category': 'Collectibles',
  'Chain': 'Klaytn',
  'Twitter followers': 11400,
  'Ownership %': 34.0,
  'Volume (USD) in M': 0.0014416,
  'Floor (USD)': 1.696,
  'Gas Volume (USD) in M': 0.0002142,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Medium gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Highly recommended'},
 {'Collection': '[TREASURES CLUB x SEOBOBIN] YOU ARE THE TREASURE',
  '24 hs %': 0.0,
  '7 d %': -31.77,
  'Owners': 351,
  'Items': 600,
  'Category': 'Music',
  'Chain': 'Klaytn',
  'Twitter followers': 0,
  'Ownership %': 58.5,
  'Volume (USD) in M': 0.000148824,
  'Floor (USD)': 24.168,
  'Gas Volume (USD) in M': 2.21e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Strange Sound Club',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 11,
  'Items': 31,
  'Category': 'Music',
  'Chain': 'Klaytn',
  'Twitter followers': 1705,
  'Ownership %': 35.48387097,
  'Volume (USD) in M': 4.66e-06,
  'Floor (USD)': 25.44,
  'Gas Volume (USD) in M': 6.93e-07,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Not interesting',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Lil 9ap - Limatic',
  '24 hs %': -100.0,
  '7 d %': 0.0,
  'Owners': 93,
  'Items': 1,
  'Category': 'Music',
  'Chain': 'Klaytn',
  'Twitter followers': 0,
  'Ownership %': 9300.0,
  'Volume (USD) in M': 3.94e-05,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 5.86e-06,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'SQUARE Records',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 8,
  'Items': 20,
  'Category': 'Music',
  'Chain': 'Klaytn',
  'Twitter followers': 129,
  'Ownership %': 40.0,
  'Volume (USD) in M': 3.39e-06,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 5.04e-07,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Not interesting',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Kwani Studio',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 2,
  'Items': 2,
  'Category': 'Music',
  'Chain': 'Klaytn',
  'Twitter followers': 0,
  'Ownership %': 100.0,
  'Volume (USD) in M': 8.48e-07,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 1.26e-07,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Not interesting',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Dragonsky',
  '24 hs %': 0.0,
  '7 d %': -100.0,
  'Owners': 68,
  'Items': 294,
  'Category': 'Photography',
  'Chain': 'Klaytn',
  'Twitter followers': 3837,
  'Ownership %': 23.1292517,
  'Volume (USD) in M': 2.88e-05,
  'Floor (USD)': 6.36,
  'Gas Volume (USD) in M': 4.28e-06,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Dragonsky Collaboration',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 6,
  'Items': 15,
  'Category': 'Photography',
  'Chain': 'Klaytn',
  'Twitter followers': 3837,
  'Ownership %': 40.0,
  'Volume (USD) in M': 2.54e-06,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 3.78e-07,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Not interesting',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'the hami flowers',
  '24 hs %': 0.0,
  '7 d %': -100.0,
  'Owners': 10,
  'Items': 27,
  'Category': 'Photography',
  'Chain': 'Klaytn',
  'Twitter followers': 19,
  'Ownership %': 37.03703704,
  'Volume (USD) in M': 4.24e-06,
  'Floor (USD)': 4.24,
  'Gas Volume (USD) in M': 6.3e-07,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Not interesting',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Dragonsky Edition',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 1100,
  'Items': 15,
  'Category': 'Photography',
  'Chain': 'Klaytn',
  'Twitter followers': 3837,
  'Ownership %': 7333.333333,
  'Volume (USD) in M': 0.0004664,
  'Floor (USD)': 0.0848,
  'Gas Volume (USD) in M': 6.93e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'byThere',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 10,
  'Items': 14,
  'Category': 'Photography',
  'Chain': 'Klaytn',
  'Twitter followers': 297,
  'Ownership %': 71.42857143,
  'Volume (USD) in M': 4.24e-06,
  'Floor (USD)': 0.0,
  'Gas Volume (USD) in M': 6.3e-07,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Not interesting',
  'Gas Status': 'Not interesting',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'ProjectWITH',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 9,
  'Items': 18,
  'Category': 'Sports',
  'Chain': 'Klaytn',
  'Twitter followers': 1682,
  'Ownership %': 50.0,
  'Volume (USD) in M': 3.82e-06,
  'Floor (USD)': 212.0,
  'Gas Volume (USD) in M': 5.67e-07,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Not interesting',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'StatNFT',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 117,
  'Items': 960,
  'Category': 'Sports',
  'Chain': 'Klaytn',
  'Twitter followers': 1529,
  'Ownership %': 12.1875,
  'Volume (USD) in M': 4.96e-05,
  'Floor (USD)': 1.696,
  'Gas Volume (USD) in M': 7.37e-06,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'SNKRZ NFT',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 4,
  'Items': 70,
  'Category': 'Sports',
  'Chain': 'Klaytn',
  'Twitter followers': 39000,
  'Ownership %': 5.714285714,
  'Volume (USD) in M': 1.7e-06,
  'Floor (USD)': 207.76,
  'Gas Volume (USD) in M': 2.52e-07,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Not interesting',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'TEAMKOREA HOHO',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 363,
  'Items': 3000,
  'Category': 'Sports',
  'Chain': 'Klaytn',
  'Twitter followers': 0,
  'Ownership %': 12.1,
  'Volume (USD) in M': 0.000153912,
  'Floor (USD)': 1.272,
  'Gas Volume (USD) in M': 2.29e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'yamfers junior',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 203,
  'Items': 431,
  'Category': 'Sports',
  'Chain': 'Klaytn',
  'Twitter followers': 0,
  'Ownership %': 47.09976798,
  'Volume (USD) in M': 8.61e-05,
  'Floor (USD)': 1.696,
  'Gas Volume (USD) in M': 1.28e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Not interesting',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'SYLTARE-OFFICIAL',
  '24 hs %': 0.0,
  '7 d %': -100.0,
  'Owners': 2300,
  'Items': 9400,
  'Category': 'Trading Cards',
  'Chain': 'Klaytn',
  'Twitter followers': 19900,
  'Ownership %': 24.46808511,
  'Volume (USD) in M': 0.0009752,
  'Floor (USD)': 1394.96,
  'Gas Volume (USD) in M': 0.0001449,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'SYLTARE, Frozen',
  '24 hs %': 0.0,
  '7 d %': 0.0,
  'Owners': 2500,
  'Items': 9100,
  'Category': 'Trading Cards',
  'Chain': 'Klaytn',
  'Twitter followers': 19900,
  'Ownership %': 27.47252747,
  'Volume (USD) in M': 0.00106,
  'Floor (USD)': 424.0,
  'Gas Volume (USD) in M': 0.0001575,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Top Collectors',
  'Gas Status': 'Medium gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'ArcheWorld_FandomCard',
  '24 hs %': 4.77,
  '7 d %': 0.0,
  'Owners': 735,
  'Items': 2200,
  'Category': 'Trading Cards',
  'Chain': 'Klaytn',
  'Twitter followers': 13000,
  'Ownership %': 33.40909091,
  'Volume (USD) in M': 0.00031164,
  'Floor (USD)': 245.92,
  'Gas Volume (USD) in M': 4.63e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'ArcheWorld_Land',
  '24 hs %': -6.4,
  '7 d %': 0.0,
  'Owners': 478,
  'Items': 1400,
  'Category': 'Trading Cards',
  'Chain': 'Klaytn',
  'Twitter followers': 13000,
  'Ownership %': 34.14285714,
  'Volume (USD) in M': 0.000202672,
  'Floor (USD)': 220.48,
  'Gas Volume (USD) in M': 3.01e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Puzzle Fantasy',
  '24 hs %': -100.0,
  '7 d %': 0.0,
  'Owners': 518,
  'Items': 5000,
  'Category': 'Trading Cards',
  'Chain': 'Klaytn',
  'Twitter followers': 3785,
  'Ownership %': 10.36,
  'Volume (USD) in M': 0.000219632,
  'Floor (USD)': 103.88,
  'Gas Volume (USD) in M': 3.26e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'KEROZ LAND MINT PASS',
  '24 hs %': 0.0,
  '7 d %': -37.39,
  'Owners': 691,
  'Items': 3600,
  'Category': 'Utility',
  'Chain': 'Klaytn',
  'Twitter followers': 13900,
  'Ownership %': 19.19444444,
  'Volume (USD) in M': 0.000292984,
  'Floor (USD)': 148.4,
  'Gas Volume (USD) in M': 4.35e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Potential community',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Sligthly recommended'},
 {'Collection': 'Klay Museum',
  '24 hs %': -100.0,
  '7 d %': 1900.0,
  'Owners': 539,
  'Items': 5500,
  'Category': 'Utility',
  'Chain': 'Klaytn',
  'Twitter followers': 3242,
  'Ownership %': 9.8,
  'Volume (USD) in M': 0.000228536,
  'Floor (USD)': 11.024,
  'Gas Volume (USD) in M': 3.4e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'Klanium Card',
  '24 hs %': 0.0,
  '7 d %': 55.79,
  'Owners': 1200,
  'Items': 3400,
  'Category': 'Utility',
  'Chain': 'Klaytn',
  'Twitter followers': 55400,
  'Ownership %': 35.29411765,
  'Volume (USD) in M': 0.0005088,
  'Floor (USD)': 16.112,
  'Gas Volume (USD) in M': 7.56e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Community',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Give it a chance'},
 {'Collection': 'ChartpanNFT',
  '24 hs %': -3.343,
  '7 d %': 229.1,
  'Owners': 256,
  'Items': 10000,
  'Category': 'Utility',
  'Chain': 'Klaytn',
  'Twitter followers': 3744,
  'Ownership %': 2.56,
  'Volume (USD) in M': 0.000108544,
  'Floor (USD)': 50.88,
  'Gas Volume (USD) in M': 1.61e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Middle Accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'},
 {'Collection': 'Neverland Pirateships',
  '24 hs %': 0.0,
  '7 d %': -90.39,
  'Owners': 209,
  'Items': 1000,
  'Category': 'Utility',
  'Chain': 'Klaytn',
  'Twitter followers': 2748,
  'Ownership %': 20.9,
  'Volume (USD) in M': 8.86e-05,
  'Floor (USD)': 13.992,
  'Gas Volume (USD) in M': 1.32e-05,
  'Market Share %': 0.0,
  'Growth': 'Not interesting',
  'Ownership Status': 'Not interesting',
  'Popularity': 'Emerging',
  'Accesibility': 'Highly accesible',
  'Gas Status': 'Low gas',
  'Market Status': 'Not interesting',
  'Recommendation': 'Not recommended'}]