sources:
  - name: raw_mkt_historical_gads 
    database: raw_snowflake
    schema: raw_mkt_historical_gads 
    tables:
      - name: campaign_history 
      - name: campaign_stats_metrics 
      - name: account_history 
      - name: adgroup
      - name: keyword_view
      - name: ad_history
  
  - name: raw_mkt_historical_fb
    database: raw_snowflake
    schema: raw_mkt_historical_fb
    tables:
      - name: country_per_facebook_campaign
      - name: campaign_outbound_clicks
      - name: campaign_outbound_clicks_outbound_clicks
      - name: ad_group 
      - name: ad_conversion_detail
      - name: ad_conversion_detail_conversions
      - name: ad_image_asset
      - name: ad_video_asset
      - name: ad_history
      - name: creative_history
      - name: ad_video_history
      - name: body_asset
  