sources: 
  - name: google_analytics 
    database: raw_snowflake
    schema: google_analytics
    tables:
      - name: landing_page_conversion
  - name: piwik_pro 
    database: raw_snowflake
    schema: piwik_pro
    tables:
      - name: sessions
      - name: analytics
      - name: events
