sources: 
   - name: raw_gsheets
    database: raw_snowflake
    schema: raw_gsheets
    freshness:
        warn_after: 
          count: 24
          period: hour
    loaded_at_field: _FIVETRAN_SYNCED
    tables:
      - name: eventbrite