sources: 
  - name: piwik_pro 
    database: raw
    schema: piwik
    freshness:
        warn_after: 
          count: 24
          period: hour
    loaded_at_field: data_inserted 
    tables:
      - name: sessions 
      - name: analytics
      - name: streaming 