dbt_playground:

  target: dev
  outputs:
    dev:
      type: duckdb
      path:  "md:my_db?motherduck_token={{env_var('MOTHERDUCK_TOKEN')}}"
      extensions:
        - httpfs
        - s3
      settings:
        s3_region: eu-west-3
        s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"
    
    dev_public_s3:
      type: duckdb
      schema: dbt_dev_public_s3
      path: 'md:ANALYTICS'
      threads: 16
      extensions: 
        - httpfs
        - s3
      settings:
        s3_region: eu-west-3
        s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"

    prod:
      type: duckdb
      schema: dbt_duckdb_prod
      path: 'md:ANALYTICS'
      threads: 16
      extensions: 
        - httpfs
        - s3
      settings:
        s3_region: eu-west-3
        s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"
  