import random
import pandas as pd

nfts_recos = pd.read_csv('nft_final_recommendations.csv')


new_collections = pd.DataFrame([{'7 d %':random.randint(-50,100),
                                     'Twitter followers':random.randint(int(nfts_recos['Twitter followers'].min()), int(nfts_recos['Twitter followers'].max())),
                                     'Ownership %':random.randint(0,120),
                                     'Floor (USD)':random.randint(0,10000),
                                     'Volume (USD) in M':random.randint(0, 25),
                                     'Market Share %':random.randint(0,50)},
                                 {'7 d %':random.randint(-50,100),
                                     'Twitter followers':random.randint(0,2000000),
                                     'Ownership %':random.randint(0,120),
                                     'Floor (USD)':random.randint(0,10000),
                                     'Volume (USD) in M':random.randint(0, 25),
                                     'Market Share %':random.randint(0,50)},
                                  {'7 d %':random.randint(-50,100),
                                     'Twitter followers':random.randint(0,2000000),
                                     'Ownership %':random.randint(0,120),
                                     'Floor (USD)':random.randint(0,10000),
                                     'Volume (USD) in M':random.randint(0, 25),
                                     'Market Share %':random.randint(0,50)},
                                  {'7 d %':random.randint(-50,100),
                                     'Twitter followers':random.randint(0,2000000),
                                     'Ownership %':random.randint(0,120),
                                     'Floor (USD)':random.randint(0,10000),
                                     'Volume (USD) in M':random.randint(0, 25),
                                     'Market Share %':random.randint(0,50)},
                                  {'7 d %':random.randint(-50,100),
                                     'Twitter followers':random.randint(0,2000000),
                                     'Ownership %':random.randint(0,120),
                                     'Floor (USD)':random.randint(0,10000),
                                     'Volume (USD) in M':random.randint(0, 25),
                                     'Market Share %':random.randint(0,50)},
                                  {'7 d %':random.randint(-50,100),
                                     'Twitter followers':random.randint(0,2000000),
                                     'Ownership %':random.randint(0,120),
                                     'Floor (USD)':random.randint(0,10000),
                                     'Volume (USD) in M':random.randint(0, 25),
                                     'Market Share %':random.randint(0,50)},
                                  {'7 d %':random.randint(-50,100),
                                     'Twitter followers':random.randint(0,2000000),
                                     'Ownership %':random.randint(0,120),
                                     'Floor (USD)':random.randint(0,10000),
                                     'Volume (USD) in M':random.randint(0, 25),
                                     'Market Share %':random.randint(0,50)},
                                  {'7 d %':random.randint(-50,100),
                                     'Twitter followers':random.randint(0,2000000),
                                     'Ownership %':random.randint(0,120),
                                     'Floor (USD)':random.randint(0,10000),
                                     'Volume (USD) in M':random.randint(0, 25),
                                     'Market Share %':random.randint(0,50)},
                                  {'7 d %':random.randint(-50,100),
                                     'Twitter followers':random.randint(0,2000000),
                                     'Ownership %':random.randint(0,120),
                                     'Floor (USD)':random.randint(0,10000),
                                     'Volume (USD) in M':random.randint(0, 25),
                                     'Market Share %':random.randint(0,50)},
                                  {'7 d %':random.randint(-50,100),
                                     'Twitter followers':random.randint(0,2000000),
                                     'Ownership %':random.randint(0,120),
                                     'Floor (USD)':random.randint(0,10000),
                                     'Volume (USD) in M':random.randint(0, 25),
                                     'Market Share %':random.randint(0,50)}   
                                         ])

new_collections_dict = new_collections.to_dict(orient='records')

